/* Siliguri Puja Guide service worker.
   - App shell: stale-while-revalidate from a versioned cache (VERSION/ASSETS generated by tools/build-sw.js).
   - data/puja-data.json: NETWORK-FIRST. A saved copy is used only if the network fails, and is returned with
     the header "X-Data-Source: cache" so the app can show a prominent "offline / may be outdated" banner.
   - Map tiles (other origin) are never cached here. */
const VERSION = 'spn-shell-393c4e1a7d';
const ASSETS = ["./","admin-preview.html","admin-preview.js","app.js","assets/logos/originals/siliguri-metropolitan-police.original.png","assets/logos/originals/west-bengal-police.original.webp","assets/logos/siliguri-metropolitan-police.png","assets/logos/west-bengal-police.png","branding.js","icons/apple-touch-icon.png","icons/favicon-32.png","icons/icon-192.png","icons/icon-512.png","icons/icon-maskable-512.png","index.html","logic.js","manifest.webmanifest","offline.html","styles.css","theme-init.js","vendor/leaflet/LICENSE","vendor/leaflet/images/layers-2x.png","vendor/leaflet/images/layers.png","vendor/leaflet/images/marker-icon-2x.png","vendor/leaflet/images/marker-icon.png","vendor/leaflet/images/marker-shadow.png","vendor/leaflet/leaflet.css","vendor/leaflet/leaflet.js","vendor/markercluster/LICENSE","vendor/markercluster/MarkerCluster.Default.css","vendor/markercluster/MarkerCluster.css","vendor/markercluster/leaflet.markercluster.js"];
const DATA_CACHE = 'spn-data-v1';
const DATA_PATH = 'data/puja-data.json';
const NETWORK_TIMEOUT_MS = 8000;

self.addEventListener('install', (e) => {
  // Core files must all be cached. Optional institutional logos (assets/logos/) are cached individually and
  // a missing/failed logo never fails the install.
  const optional = (a) => a.startsWith('assets/logos/');
  e.waitUntil(caches.open(VERSION).then(async (c) => {
    await c.addAll(ASSETS.filter((a) => !optional(a)));
    await Promise.all(ASSETS.filter(optional).map((a) => c.add(a).catch(() => {})));
  }).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('spn-shell-') && k !== VERSION).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

function dataKey() { return new URL(DATA_PATH, self.registration.scope).href; }

async function dataNetworkFirst() {
  const cache = await caches.open(DATA_CACHE);
  try {
    const ctl = new AbortController();
    const t = setTimeout(() => ctl.abort(), NETWORK_TIMEOUT_MS);
    const res = await fetch(dataKey() + '?cb=' + Date.now(), { cache: 'no-store', signal: ctl.signal });
    clearTimeout(t);
    if (!res.ok) throw new Error('bad status ' + res.status);
    try { JSON.parse(await res.clone().text()); } catch (err) { return res; } // never save a corrupt file
    await cache.put(dataKey(), res.clone());
    return res;
  } catch (err) {
    const saved = await cache.match(dataKey());
    if (!saved) return new Response('', { status: 503, statusText: 'Data unavailable' });
    const headers = new Headers(saved.headers);
    headers.set('X-Data-Source', 'cache');
    headers.set('Cache-Control', 'no-store');
    return new Response(await saved.blob(), { status: 200, headers });
  }
}

async function staleWhileRevalidate(req) {
  const cache = await caches.open(VERSION);
  const hit = await cache.match(req, { ignoreSearch: true });
  const net = fetch(req).then((res) => { if (res && res.ok && res.type === 'basic') cache.put(req, res.clone()); return res; });
  if (hit) { net.catch(() => {}); return hit; }
  return net;
}

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (url.href.startsWith(dataKey())) { e.respondWith(dataNetworkFirst()); return; }
  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      const cache = await caches.open(VERSION);
      const hit = await cache.match(req, { ignoreSearch: true });
      if (hit) { fetch(req).then((r) => { if (r && r.ok) cache.put(req, r.clone()); }).catch(() => {}); return hit; }
      try { return await fetch(req); }
      catch (err) { return (await cache.match('offline.html')) || new Response('Offline', { status: 503 }); }
    })());
    return;
  }
  e.respondWith(staleWhileRevalidate(req).catch(() => caches.match(req, { ignoreSearch: true }).then((r) => r || new Response('', { status: 504 }))));
});
